version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - vscode-extensions:/home/vscode/.vscode-server/extensions
    command: sleep infinity
    env_file:
      - ../snc/.env
    environment:
      - PYTHONPATH=/workspace
      - POSTGRES_HOST=db
    
  db:
    image: postgres:15-alpine
    env_file:
      - ../snc/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  vscode-extensions: